use crate::{
    db::Database,
    keygen::local::LocalKeyGenerator,
    models::{KeyAlgorithm, SshKey, Target, TargetType},
    ssh::{
        dirname_remote_path, join_remote_path, quote_remote_path, quote_shell,
        remote_private_key_path, run_remote_command,
    },
    Error, Result,
};
use chrono::Utc;
use std::path::{Path, PathBuf};

/// Alias shown for the Phase-1 local machine in the `targets` table. SSH keys
/// created in Phase 1 are associated with this row so the connection layer can
/// resolve which machine (and where on that machine) a key lives on.
const LOCAL_TARGET_ALIAS: &str = "Local Machine";

/// SSH key management service for standalone local keys.
pub struct SshKeyService {
    db: Database,
}

impl SshKeyService {
    pub fn new(db: Database) -> Self {
        Self { db }
    }

    /// Generate a new SSH key pair in an isolated directory.
    ///
    /// Keys are stored in the local target's configured key base directory,
    /// under `<directory>/id_<algorithm>`.
    /// The `directory` must be ASCII-safe (no spaces, only alphanumeric + dash/underscore).
    ///
    /// The key is associated with the Phase-1 local target, which is created on
    /// demand if it does not yet exist (so the `ssh_keys.target_id` FK always
    /// resolves). The key material itself is immutable; to edit the editable
    /// fields (directory, remark) after creation, use
    /// [`SshKeyService::update_key`].
    pub async fn create_key(
        &self,
        directory: String,
        algorithm: KeyAlgorithm,
        comment: String,
        remark: String,
    ) -> Result<SshKey> {
        let target_id = self.ensure_local_target().await?;
        self.create_key_for_target(target_id, directory, algorithm, comment, remark)
            .await
    }

    /// Generate a new SSH key pair on the selected target. Remote target keys
    /// are generated by `ssh-keygen` on the server; only the public key and
    /// metadata are copied back into the local database.
    pub async fn create_key_for_target(
        &self,
        target_id: i64,
        directory: String,
        algorithm: KeyAlgorithm,
        comment: String,
        remark: String,
    ) -> Result<SshKey> {
        let target = self
            .db
            .targets()
            .find_by_id(target_id)
            .await?
            .ok_or_else(|| Error::NotFound("Target not found".into()))?;

        match target.target_type {
            TargetType::Local => {
                self.create_local_key_for_target(&target, directory, algorithm, comment, remark)
                    .await
            }
            TargetType::Remote => {
                self.create_remote_key_for_target(&target, directory, algorithm, comment, remark)
                    .await
            }
        }
    }

    async fn create_local_key_for_target(
        &self,
        target: &Target,
        directory: String,
        algorithm: KeyAlgorithm,
        comment: String,
        remark: String,
    ) -> Result<SshKey> {
        let directory = directory.trim().to_string();
        // Validate directory is ASCII-safe
        if !directory
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(Error::Validation(
                "Directory must contain only ASCII letters, digits, hyphens, and underscores"
                    .into(),
            ));
        }
        if directory.is_empty() {
            return Err(Error::Validation("Directory is required".into()));
        }

        // The comment (conventionally an email) identifies the key's owner. It is
        // appended verbatim to the public key line, so it must not contain
        // whitespace — an embedded space would split the key line.
        let comment = comment.trim().to_string();
        if comment.is_empty() {
            return Err(Error::Validation("Comment/email is required".into()));
        }
        if comment.chars().any(char::is_whitespace) {
            return Err(Error::Validation(
                "Comment must not contain whitespace (use an email address)".into(),
            ));
        }

        // Check for duplicate directory
        if self
            .db
            .ssh_keys()
            .find_by_directory_and_target(&directory, target.id)
            .await?
            .is_some()
        {
            return Err(Error::AlreadyExists(format!(
                "SSH key with directory '{}' already exists",
                directory
            )));
        }

        let base_dir = expand_local_key_base_dir(&target.key_base_dir)?;
        tokio::fs::create_dir_all(&base_dir).await?;
        let key_dir = base_dir.join(&directory);
        match tokio::fs::create_dir(&key_dir).await {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                return Err(Error::AlreadyExists(format!(
                    "Directory already exists: {}",
                    display_local_path(&key_dir)
                )));
            }
            Err(e) => return Err(Error::Io(e)),
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            tokio::fs::set_permissions(&key_dir, std::fs::Permissions::from_mode(0o700)).await?;
        }

        // Key file path: ~/.ssh/deploykeys/<directory>/id_<algorithm>
        let key_filename = format!("id_{}", algorithm.to_string().to_lowercase());
        let private_key_path = key_dir.join(&key_filename);

        // Generate key pair (CPU-bound, run on blocking thread). The comment
        // (typically an email) is embedded as the identity at the end of the
        // public key line.
        let gen_algorithm = algorithm.clone();
        let gen_path = private_key_path.clone();
        let gen_comment = comment.clone();
        let key_pair = match tokio::task::spawn_blocking(move || {
            LocalKeyGenerator::generate(gen_algorithm, &gen_path, &gen_comment)
        })
        .await
        {
            Ok(Ok(key_pair)) => key_pair,
            Ok(Err(e)) => {
                let _ = tokio::fs::remove_dir(&key_dir).await;
                return Err(e);
            }
            Err(e) => {
                let _ = tokio::fs::remove_dir(&key_dir).await;
                return Err(Error::Other(format!("Key generation task failed: {}", e)));
            }
        };

        let public_key_path = private_key_path.with_extension("pub");

        let ssh_key = SshKey {
            id: 0,
            directory,
            algorithm,
            public_key: key_pair.public_key,
            public_key_fingerprint: key_pair.fingerprint,
            private_key_path: private_key_path.to_string_lossy().to_string(),
            public_key_path: public_key_path.to_string_lossy().to_string(),
            comment,
            remark: remark.trim().to_string(),
            target_id: target.id,
            created_at: Utc::now(),
        };

        let id = self.db.ssh_keys().create(&ssh_key).await?;
        Ok(SshKey { id, ..ssh_key })
    }

    async fn create_remote_key_for_target(
        &self,
        target: &Target,
        directory: String,
        algorithm: KeyAlgorithm,
        comment: String,
        remark: String,
    ) -> Result<SshKey> {
        let directory = validate_directory(directory)?;
        let comment = validate_comment(comment)?;
        if self
            .db
            .ssh_keys()
            .find_by_directory_and_target(&directory, target.id)
            .await?
            .is_some()
        {
            return Err(Error::AlreadyExists(format!(
                "SSH key with directory '{}' already exists on this target",
                directory
            )));
        }

        let algorithm_name = algorithm.to_string();
        let private_key_path = remote_private_key_path(target, &directory, &algorithm_name);
        let public_key_path = format!("{private_key_path}.pub");
        let key_dir = dirname_remote_path(&private_key_path)
            .ok_or_else(|| Error::Validation("Remote private key path has no directory".into()))?;
        let keygen_args = remote_keygen_args(&algorithm, &comment, &private_key_path);
        let exists_message = format!("SSH key directory already exists: {key_dir}");
        let command = format!(
            "set -eu; \
             base={base}; \
             key_dir={key_dir}; \
             private_key={private_key}; \
             public_key={public_key}; \
             created_dir=0; \
             cleanup() {{ if [ \"$created_dir\" = 1 ]; then rm -rf -- \"$key_dir\"; fi; }}; \
             trap cleanup EXIT; \
             mkdir -p -- \"$base\"; \
             if ! mkdir -- \"$key_dir\"; then printf '%s\\n' {exists_message} >&2; exit 73; fi; \
             created_dir=1; \
             chmod 700 -- \"$base\" \"$key_dir\"; \
             test ! -e \"$private_key\" && test ! -e \"$public_key\"; \
             ssh-keygen -q {keygen_args} < /dev/null; \
             chmod 600 -- \"$private_key\"; \
             chmod 644 -- \"$public_key\"; \
             printf '%s\\n' \"$(cat \"$public_key\")\"; \
             ssh-keygen -l -E sha256 -f \"$public_key\" | awk '{{print $2}}'; \
             created_dir=0; \
             trap - EXIT",
            base = quote_remote_path(&target.key_base_dir),
            key_dir = quote_remote_path(&key_dir),
            private_key = quote_remote_path(&private_key_path),
            public_key = quote_remote_path(&public_key_path),
            exists_message = quote_shell(&exists_message),
        );
        let output = run_remote_command(target, &command).await?;
        let mut lines = output.stdout.lines().filter(|line| !line.trim().is_empty());
        let public_key = lines
            .next()
            .ok_or_else(|| Error::KeyGen("Remote ssh-keygen did not return a public key".into()))?
            .trim()
            .to_string();
        let fingerprint = lines
            .next()
            .ok_or_else(|| Error::KeyGen("Remote ssh-keygen did not return a fingerprint".into()))?
            .trim()
            .to_string();

        let ssh_key = SshKey {
            id: 0,
            directory,
            algorithm,
            public_key,
            public_key_fingerprint: fingerprint,
            private_key_path,
            public_key_path,
            comment,
            remark: remark.trim().to_string(),
            target_id: target.id,
            created_at: Utc::now(),
        };

        let id = self.db.ssh_keys().create(&ssh_key).await?;
        Ok(SshKey { id, ..ssh_key })
    }

    /// List all SSH keys for a given target.
    pub async fn list_keys(&self, target_id: i64) -> Result<Vec<SshKey>> {
        self.db.ssh_keys().list_by_target(target_id).await
    }

    /// List all SSH keys (used when target filtering is not needed).
    pub async fn list_all_keys(&self) -> Result<Vec<SshKey>> {
        self.db.ssh_keys().list_all().await
    }

    /// Get a single SSH key by ID.
    pub async fn get_key(&self, id: i64) -> Result<Option<SshKey>> {
        self.db.ssh_keys().find_by_id(id).await
    }

    /// Read the public key file content.
    pub async fn read_public_key(&self, id: i64) -> Result<String> {
        let key = self
            .db
            .ssh_keys()
            .find_by_id(id)
            .await?
            .ok_or_else(|| Error::NotFound("SSH key not found".into()))?;

        self.ensure_key_files_exist(&key).await?;

        if let Some(target) = self.db.targets().find_by_id(key.target_id).await? {
            if target.target_type == TargetType::Remote {
                let output = run_remote_command(
                    &target,
                    &format!("cat {}", quote_remote_path(&key.public_key_path)),
                )
                .await?;
                return Ok(output.stdout);
            }
        }

        let content = tokio::fs::read_to_string(&key.public_key_path)
            .await
            .map_err(Error::Io)?;

        Ok(content)
    }

    /// Delete an SSH key and its files.
    pub async fn delete_key(&self, id: i64) -> Result<()> {
        let key = self
            .db
            .ssh_keys()
            .find_by_id(id)
            .await?
            .ok_or_else(|| Error::NotFound("SSH key not found".into()))?;

        let target = self.db.targets().find_by_id(key.target_id).await?;
        if target
            .as_ref()
            .is_some_and(|target| target.target_type == TargetType::Remote)
        {
            if let Some(target) = target.as_ref() {
                let parent = dirname_remote_path(&key.private_key_path).unwrap_or_default();
                let command = format!(
                    "rm -f {private_key} {public_key}; rmdir {parent} 2>/dev/null || true",
                    private_key = quote_remote_path(&key.private_key_path),
                    public_key = quote_remote_path(&key.public_key_path),
                    parent = quote_remote_path(&parent),
                );
                let _ = run_remote_command(target, &command).await;
            }
        } else {
            // Delete key files
            let _ = tokio::fs::remove_file(&key.private_key_path).await;
            let _ = tokio::fs::remove_file(&key.public_key_path).await;

            // Try to remove the parent directory if it's empty
            if let Some(parent) = Path::new(&key.private_key_path).parent() {
                let _ = tokio::fs::remove_dir(parent).await;
            }
        }

        // Delete from database
        self.db.ssh_keys().delete(id).await?;

        Ok(())
    }

    /// Return whether the key's directory and expected key files still exist.
    pub async fn key_files_exist(&self, id: i64) -> Result<bool> {
        let key = self
            .db
            .ssh_keys()
            .find_by_id(id)
            .await?
            .ok_or_else(|| Error::NotFound("SSH key not found".into()))?;

        Ok(key_files_exist(&key).await)
    }

    /// Update the editable fields of an SSH key: its directory and its remark.
    ///
    /// The key material (and the `comment`/email embedded in the public key line)
    /// is immutable; only the directory name and the free-form remark can change.
    /// Changing the directory renames the containing folder on disk and rewrites
    /// the stored file paths to match. Changing only the remark touches no files.
    pub async fn update_key(&self, id: i64, directory: &str, remark: &str) -> Result<SshKey> {
        let new_directory = directory.trim();
        if new_directory.is_empty() {
            return Err(Error::Validation("Directory cannot be empty".into()));
        }
        if !new_directory
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(Error::Validation(
                "Directory must contain only ASCII letters, digits, hyphens, and underscores"
                    .into(),
            ));
        }
        let new_remark = remark.trim().to_string();

        let key = self
            .db
            .ssh_keys()
            .find_by_id(id)
            .await?
            .ok_or_else(|| Error::NotFound("SSH key not found".into()))?;

        self.ensure_key_files_exist(&key).await?;

        // If the directory is unchanged, there is nothing to move on disk — just
        // persist the remark and the (unchanged) paths.
        if key.directory == new_directory {
            self.db
                .ssh_keys()
                .update_key(
                    id,
                    new_directory,
                    &new_remark,
                    &key.private_key_path,
                    &key.public_key_path,
                )
                .await?;

            return Ok(SshKey {
                remark: new_remark,
                ..key
            });
        }

        if self
            .db
            .ssh_keys()
            .find_by_directory_and_target(new_directory, key.target_id)
            .await?
            .is_some()
        {
            return Err(Error::AlreadyExists(format!(
                "SSH key with directory '{}' already exists",
                new_directory
            )));
        }

        let target = self.db.targets().find_by_id(key.target_id).await?;
        if let Some(target) = target.as_ref() {
            if target.target_type == TargetType::Remote {
                return self
                    .update_remote_key(id, key, target, new_directory, &new_remark)
                    .await;
            }
        }

        let old_dir = Path::new(&key.private_key_path)
            .parent()
            .ok_or_else(|| Error::Validation("SSH key path has no parent directory".into()))?;
        let new_dir = old_dir
            .parent()
            .ok_or_else(|| Error::Validation("SSH key directory has no parent directory".into()))?
            .join(new_directory);

        if new_dir.exists() {
            return Err(Error::AlreadyExists(format!(
                "Directory already exists: {}",
                new_dir.display()
            )));
        }

        tokio::fs::rename(old_dir, &new_dir).await?;

        let private_file_name = Path::new(&key.private_key_path)
            .file_name()
            .ok_or_else(|| Error::Validation("SSH private key path has no file name".into()))?;
        let public_file_name = Path::new(&key.public_key_path)
            .file_name()
            .ok_or_else(|| Error::Validation("SSH public key path has no file name".into()))?;
        let private_key_path = new_dir.join(private_file_name);
        let public_key_path = new_dir.join(public_file_name);

        if let Err(e) = self
            .db
            .ssh_keys()
            .update_key(
                id,
                new_directory,
                &new_remark,
                &private_key_path.to_string_lossy(),
                &public_key_path.to_string_lossy(),
            )
            .await
        {
            // Roll back the on-disk rename so the DB and filesystem stay in sync.
            let _ = tokio::fs::rename(&new_dir, old_dir).await;
            return Err(e);
        }

        Ok(SshKey {
            directory: new_directory.to_string(),
            remark: new_remark,
            private_key_path: private_key_path.to_string_lossy().to_string(),
            public_key_path: public_key_path.to_string_lossy().to_string(),
            ..key
        })
    }

    /// Ensure the Phase-1 local target row exists and return its id.
    ///
    /// `ssh_keys.target_id` is a FK into `targets(id)`; without a row here the
    /// insert fails with `FOREIGN KEY constraint failed`. We look the target up
    /// by its stable alias, and create it on first use with `key_base_dir`
    /// pointing at the same directory keys are actually written to.
    async fn ensure_local_target(&self) -> Result<i64> {
        if let Some(existing) = self.db.targets().find_by_alias(LOCAL_TARGET_ALIAS).await? {
            return Ok(existing.id);
        }

        let target = crate::models::Target {
            id: 0,
            target_type: crate::models::TargetType::Local,
            alias: LOCAL_TARGET_ALIAS.to_string(),
            os: detect_os(),
            host: None,
            port: None,
            username: None,
            auth_method: None,
            auth_ref: None,
            key_base_dir: "~/.ssh/deploykeys".to_string(),
            status: crate::models::TargetStatus::Active,
            host_key_fingerprint: None,
            created_at: Utc::now(),
            last_checked_at: Some(Utc::now()),
        };
        let id = self.db.targets().create(&target).await?;
        Ok(id)
    }
}

fn detect_os() -> crate::models::OsType {
    if cfg!(target_os = "macos") {
        crate::models::OsType::MacOs
    } else if cfg!(target_os = "linux") {
        crate::models::OsType::Linux
    } else if cfg!(target_os = "windows") {
        crate::models::OsType::Windows
    } else {
        crate::models::OsType::Unknown
    }
}

fn resolve_ssh_keys_base_dir() -> Result<PathBuf> {
    let home =
        dirs::home_dir().ok_or_else(|| Error::Other("Could not find home directory".into()))?;
    Ok(home.join(".ssh").join("deploykeys"))
}

fn expand_local_key_base_dir(value: &str) -> Result<PathBuf> {
    let value = value.trim();
    if value.is_empty() {
        return resolve_ssh_keys_base_dir();
    }

    let path = if value == "~" {
        dirs::home_dir().ok_or_else(|| Error::Other("Could not find home directory".into()))?
    } else if let Some(rest) = value.strip_prefix("~/") {
        dirs::home_dir()
            .ok_or_else(|| Error::Other("Could not find home directory".into()))?
            .join(rest)
    } else {
        PathBuf::from(value)
    };

    if path.is_absolute() {
        Ok(path)
    } else {
        Err(Error::Validation(
            "Local SSH key storage directory must be absolute or start with ~/".into(),
        ))
    }
}

fn display_local_path(path: &Path) -> String {
    if let Some(home) = dirs::home_dir() {
        if path == home {
            return "~".to_string();
        }
        if let Ok(rest) = path.strip_prefix(&home) {
            return format!("~/{}", rest.to_string_lossy());
        }
    }
    path.display().to_string()
}

async fn key_files_exist(key: &SshKey) -> bool {
    let private_path = Path::new(&key.private_key_path);
    let public_path = Path::new(&key.public_key_path);

    private_path
        .parent()
        .is_some_and(|dir| dir.exists() && dir.is_dir())
        && private_path.exists()
        && public_path.exists()
}

impl SshKeyService {
    async fn ensure_key_files_exist(&self, key: &SshKey) -> Result<()> {
        if key_files_exist(key).await {
            return Ok(());
        }

        if let Some(target) = self.db.targets().find_by_id(key.target_id).await? {
            if target.target_type == TargetType::Remote {
                let command = format!(
                    "test -d {dir} && test -f {private_key} && test -f {public_key}",
                    dir = quote_remote_path(
                        &dirname_remote_path(&key.private_key_path).unwrap_or_default()
                    ),
                    private_key = quote_remote_path(&key.private_key_path),
                    public_key = quote_remote_path(&key.public_key_path),
                );
                run_remote_command(&target, &command).await?;
                return Ok(());
            }
        }

        Err(Error::NotFound(
            "SSH key directory or key files are missing".into(),
        ))
    }

    async fn update_remote_key(
        &self,
        id: i64,
        key: SshKey,
        target: &Target,
        new_directory: &str,
        new_remark: &str,
    ) -> Result<SshKey> {
        if key.directory == new_directory {
            self.db
                .ssh_keys()
                .update_key(
                    id,
                    new_directory,
                    new_remark,
                    &key.private_key_path,
                    &key.public_key_path,
                )
                .await?;
            return Ok(SshKey {
                remark: new_remark.to_string(),
                ..key
            });
        }

        let old_dir = dirname_remote_path(&key.private_key_path)
            .ok_or_else(|| Error::Validation("SSH key path has no parent directory".into()))?;
        let parent = dirname_remote_path(&old_dir)
            .ok_or_else(|| Error::Validation("SSH key directory has no parent directory".into()))?;
        let new_dir = join_remote_path(&parent, new_directory);
        let private_name = key
            .private_key_path
            .rsplit_once('/')
            .map(|(_, name)| name)
            .ok_or_else(|| Error::Validation("SSH private key path has no file name".into()))?;
        let public_name = key
            .public_key_path
            .rsplit_once('/')
            .map(|(_, name)| name)
            .ok_or_else(|| Error::Validation("SSH public key path has no file name".into()))?;
        let private_key_path = join_remote_path(&new_dir, private_name);
        let public_key_path = join_remote_path(&new_dir, public_name);

        let command = format!(
            "test ! -e {new_dir}; mv {old_dir} {new_dir}",
            old_dir = quote_remote_path(&old_dir),
            new_dir = quote_remote_path(&new_dir),
        );
        run_remote_command(target, &command).await?;

        if let Err(e) = self
            .db
            .ssh_keys()
            .update_key(
                id,
                new_directory,
                new_remark,
                &private_key_path,
                &public_key_path,
            )
            .await
        {
            let rollback = format!(
                "test ! -e {old_dir}; mv {new_dir} {old_dir}",
                old_dir = quote_remote_path(&old_dir),
                new_dir = quote_remote_path(&new_dir),
            );
            let _ = run_remote_command(target, &rollback).await;
            return Err(e);
        }

        Ok(SshKey {
            directory: new_directory.to_string(),
            remark: new_remark.to_string(),
            private_key_path,
            public_key_path,
            ..key
        })
    }
}

fn validate_directory(directory: String) -> Result<String> {
    let directory = directory.trim().to_string();
    if !directory
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(Error::Validation(
            "Directory must contain only ASCII letters, digits, hyphens, and underscores".into(),
        ));
    }
    if directory.is_empty() {
        return Err(Error::Validation("Directory is required".into()));
    }
    Ok(directory)
}

fn validate_comment(comment: String) -> Result<String> {
    let comment = comment.trim().to_string();
    if comment.is_empty() {
        return Err(Error::Validation("Comment/email is required".into()));
    }
    if comment.chars().any(char::is_whitespace) {
        return Err(Error::Validation(
            "Comment must not contain whitespace (use an email address)".into(),
        ));
    }
    Ok(comment)
}

fn remote_keygen_args(algorithm: &KeyAlgorithm, comment: &str, private_key_path: &str) -> String {
    let mut args = match algorithm {
        KeyAlgorithm::Ed25519 => vec!["-t".to_string(), "ed25519".to_string()],
        KeyAlgorithm::Rsa2048 => vec![
            "-t".to_string(),
            "rsa".to_string(),
            "-b".to_string(),
            "2048".to_string(),
        ],
        KeyAlgorithm::Rsa4096 => vec![
            "-t".to_string(),
            "rsa".to_string(),
            "-b".to_string(),
            "4096".to_string(),
        ],
        KeyAlgorithm::EcdsaP256 => vec![
            "-t".to_string(),
            "ecdsa".to_string(),
            "-b".to_string(),
            "256".to_string(),
        ],
        KeyAlgorithm::EcdsaP384 => vec![
            "-t".to_string(),
            "ecdsa".to_string(),
            "-b".to_string(),
            "384".to_string(),
        ],
        KeyAlgorithm::EcdsaP521 => vec![
            "-t".to_string(),
            "ecdsa".to_string(),
            "-b".to_string(),
            "521".to_string(),
        ],
    };
    args.extend([
        "-N".to_string(),
        String::new(),
        "-C".to_string(),
        comment.to_string(),
        "-f".to_string(),
    ]);
    let mut parts = args
        .into_iter()
        .map(|arg| quote_shell(&arg))
        .collect::<Vec<_>>();
    parts.push(quote_remote_path(private_key_path));
    parts.join(" ")
}
